import GlobalProvider from "@/components/Application/GlobalProvider";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import PerformanceOptimizer from "@/components/Performance/PerformanceOptimizer";

// Using system fonts to avoid external font fetch issues

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* No external font preloads to ensure offline-safe builds */}
      </head>
      <body
        className={`antialiased`}
      >
        <PerformanceOptimizer />
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
